export const SAGA_GET_ALL_SERVISES = 'GET_ALL_SERVISES'
export const GET_ALL_SERVISES = 'GET_ALL_SERVISES'
export const SAGA_GET_SERVISES_DETAILS = 'SAGA_GET_SERVISES_DETAILS'
export const GET_SERVISES_DETAILS = 'GET_SERVISES_DETAILS'
